#!/bin/bash

set -ex

git clone https://github.com/plicease-pr/Dist-Zilla.git
cd Dist-Zilla
git checkout graham/archiver
dzil-dzil authordeps | dzil-cpanm -n
dzil-dzil run 'dzil-cpanm -n .'
cd ..
rm -rf Dist-Zilla
dzil-cpanm -n maint/Dist-Zilla-Plugin-Libarchive-0.01.tar.gz
